INSERT INTO TB_USUARIO (LOGIN, SENHA, DATA_CADASTRO) VALUES ('user@zup.com', '$2a$10$ni82xTO89bDURUYDNKwah.CpLv7GMIT62HTtKOTMrhLiWKAjS1yc.', CURRENT_DATE());

INSERT INTO TB_CATEGORIA (NOME, CATEGORIA_MAE_ID) VALUES ('Brinquedos', null);